### PR TITLE
Small change on http server - don't call os.getcwd() every translate_…

### PR DESCRIPTION
**Pull request by mykaul**
…path()

It's not really needed, I think.

### CODE REVIEW

**Comment by mykaul** [comment]
It does NOT fix https://github.com/lago-project/lago-ost-plugin/issues/46

**Comment by mykaul** [comment]
@ifireball - any idea what is the failure?
```
17:13:36 py27 runtests: PYTHONHASHSEED='4101834618'
17:13:36 py27 runtests: commands[0] | /home/jenkins/workspace/lago-ost-plugin_master_github_check-patch-el7-x86_64/lago-ost-plugin/scripts/check_style.sh
17:13:36 yapf 0.22.0
17:13:36 running yapf on the following files:
17:13:36 ovirtlago/utils.py
17:13:36 ERROR: InvocationError for command '/home/jenkins/workspace/lago-ost-plugin_master_github_check-patch-el7-x86_64/lago-ost-plugin/scripts/check_style.sh' (exited with code 1)
17:13:36 ___________________________________ summary ____________________________________
17:13:36 ERROR:   py27: commands failed
```

**Comment by gbenhaim** [comment]
@mykaul https://github.com/lago-project/lago-ost-plugin/pull/51 should fix the issue.

I expect the fc28 job to fail because repoman for fedora 28 hasn't been released yet.
We have an open ticket on it: https://ovirt-jira.atlassian.net/browse/OVIRT-2163

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
